Added comments in pep8task_Teterin_Roman.py
IlyaOrlov/PythonCourse2 pull request #12
Opened 2020-09-28 11:14 UTC by rateterin

2020-09-28 11:20 UTC, IlyaOrlov requested changes

2020-09-28 11:20 UTC, IlyaOrlov commented on Practice/Teterin_Roman/pep8task_Teterin_Roman.py
> +          f = open(output, 'r') # относительный отступ 2 пробела, вместо 4
А может, здесь и в 25-й строке наоборот отступы лишние? В чем разница?

2020-09-28 12:16 UTC, rateterin commented on Practice/Teterin_Roman/pep8task_Teterin_Roman.py
> +          f = open(output, 'r') # относительный отступ 2 пробела, вместо 4
Точно, следовало написать "не понятно, к какому блоку относятся строки 24 и 25

2020-09-28 12:18 UTC, rateterin reviewed
Поправил по строкам 24 и 25 в соответствии с рекомендациями

2020-09-28 14:04 UTC, IlyaOrlov commented
> Поправил по строкам 24 и 25 в соответствии с рекомендациями

ОК. Но можно еще кое-какие ошибки в файле найти. Например, в импортах, в именах функций и классов...

2020-09-29 18:49 UTC, IlyaOrlov approved these changes

2020-09-29 18:49 UTC, merged