pep8 task update
IlyaOrlov/PythonCourse2 pull request #14
Opened 2020-09-28 16:48 UTC by Irene-lab80

2020-09-29 19:02 UTC, IlyaOrlov requested changes

2020-09-29 19:02 UTC, IlyaOrlov commented on Practice/IrinaZ/pep8task.py
> +        # Ошибка в "dirname": слова в названиях функций должны быть разделены "_"
На самом деле PyCharm здесь и в случае с hashname ругается на то, что таких слов нет в его внутреннем словаре, поэтому он предполагает опечатку. На практике такие имена, если они удобочитаемы, вполне допустимы: например, hashname, filename, hashset - сразу ясно из каких слов они состоят. А например, variableforint, connectiontoserver - достаточно сложны для понимания с первого взгляда (лучше: variable_for_int, connection_to_server).

2020-09-30 18:35 UTC, Irene-lab80 commented on Practice/IrinaZ/pep8task.py
> +        # dirname - функция подмодуля os.path, лучше не давать такое название другой функции (?)
Ок, поняла

2020-09-30 18:45 UTC, Irene-lab80 commented on Practice/IrinaZ/pep8task.py
> +            f = open(output, 'r')  # Была ошибка в уровне вложенности: не хватало 2 пробела
Просто если пробелы лишние, будет выход из цикла. Мне показалось это нелогичным, но я очень приблизительно понимаю что делает этот код.

2020-09-30 19:41 UTC, IlyaOrlov commented on Practice/IrinaZ/pep8task.py
> +            f = open(output, 'r')  # Была ошибка в уровне вложенности: не хватало 2 пробела
Действительно, если проблемы лишние, то строки 27-28 будут выполняться вне цикла, но нелогичности в этом нет (более того, вне цикла как раз правильный вариант, т.к. лучше полностью заполнить self.map в цикле, а потом один раз записать ее в файл, чем постоянно перезаписывать этот файл на каждой итерации цикла, а операция записи в файл достаточно затратна по времени). Не имея же полного представления о решаемой здесь задаче, мы можем только констатировать неопределенность с отступами (в чем, собственно, и состоит ошибка), т.к. непонятно надо ли добавлять пробелы или убирать.

2020-09-30 19:42 UTC, IlyaOrlov commented
Все ОК. Надо только поправить комментарии в соответствии с замечаниями.

2020-09-30 21:29 UTC, Irene-lab80 commented on Practice/IrinaZ/pep8task.py
> +    shuffler = shuffler()
То есть должно быть Shuffler = Shuffler() ? И все что идет после этой строки относится к этому же уровню вложенности? Просто если оставить так, PyCharm Ругается и говорит, что это функция, а если убрать на другой уровень, не ругается, но вылезают другие ошибки дальше в коде.

2020-09-30 21:37 UTC, IlyaOrlov commented on Practice/IrinaZ/pep8task.py
> +    shuffler = shuffler()
Должно быть shuffler = Shuffler():
shuffler (слева) - это имя переменной, оно с маленькой буквы.
Shuffler (справа) - это имя класса, оно с большой буквы (как в строке 9).
Мы это еще разберем на предстоящей лекции, но для понимания: 
- данной конструкцией (имя класса со скобками) - Shuffler() - мы создаем экземпляр класса.
- данной конструкцией (имя переменной и знак равно) - shuffler = Shuffler() - мы связываем переменную с созданным экземпляром.
Создание экземпляра и вызов функции выглядят одинаково (поэтому их легко спутать). 
С уровнями вложенности правильно так, как у вас получилось сейчас.

2020-09-30 22:12 UTC, IlyaOrlov approved these changes

2020-09-30 22:12 UTC, merged