Create pep8task.py
IlyaOrlov/PythonCourse2 pull request #19
Opened 2020-09-30 20:55 UTC by n1kasus

fuck console, test desktop 1

2020-09-30 20:56 UTC, n1kasus commented
ссылку можно на гугл диск пожалуйста

2020-09-30 21:26 UTC, IlyaOrlov commented
> ссылку можно на гугл диск пожалуйста

https://drive.google.com/drive/folders/15XWlDTz9mEjjF30jIKFISfiL3vbxnjcC?usp=sharing

2020-09-30 23:31 UTC, n1kasus commented
Выскакивают ошибки при объединении с мастером:
Review required
At least 1 approving review is required by reviewers with write access. 
Merging is blocked
Merging can be performed automatically with 1 approving review.

2020-10-01 07:13 UTC, IlyaOrlov commented
> Выскакивают ошибки при объединении с мастером:
> Review required
> At least 1 approving review is required by reviewers with write access.
> Merging is blocked
> Merging can be performed automatically with 1 approving review.

Так чтоб в мастер отправляться, ваше решение сначала проверку должно пройти. Я проверю задание, и если замечаний не будет, отправлю в мастер.

2020-10-01 07:46 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/func2.py
> +        print("Числа равны, ничего не возвращаем")
Что возвращает функция в данной ветке?

2020-10-01 07:48 UTC, n1kasus commented on Practice/Krayukhin_Konstantin/task 2/func2.py
> +        print("Числа равны, ничего не возвращаем")
число из функции? его потом печатаем? или я не правильно понял?

2020-10-01 07:52 UTC, IlyaOrlov requested changes

2020-10-01 07:52 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/tsk1/pep8task.py
> +            os.rename(path + '/' + mp3), ( path + '/' + hashname) # Лишняя скобка?
Скобки тут определенно лишние, но не те, которые вы убрали. В этой строке вызывается функция. Вызов функции выглядит так: имя_функции(аргументы). Т.е. обязательными являются именно внешние скобки.

2020-10-01 07:52 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/tsk1/pep8task.py
> +            f = open(output, 'r') # должно быть 4 пробела
А может наоборот пробелы были лишними, т.к. непонятно, относятся ли строки 24-25 к циклу for или нет?

2020-10-01 09:50 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/func2.py
> +        print("Числа равны, ничего не возвращаем")
Под возвратом значения из функции всегда подразумевается значение, которое подставится на место вызова функции (в данном примере в строку 17). На это значение и будет указывать переменная return_number. Print к возврату значения никакого отношения не имеет. Возврат значения из функции осуществляется при помощи return (например, в строке 5 возвращается значение переменной a, в строке 8 - b). А что возвращается в ветке else, где нет **явного** return?

2020-10-12 21:41 UTC, IlyaOrlov approved these changes

2020-10-12 21:41 UTC, merged