Hello
IlyaOrlov/PythonCourse2 pull request #23
Opened 2020-10-02 13:25 UTC by taigunov

2020-10-02 13:42 UTC, IlyaOrlov requested changes

2020-10-02 13:42 UTC, IlyaOrlov commented on Practice/Taigunov/Test.py
> +if a <= b:
Хорошо. Только нужно этот код внутри функции разместить (т.е. написать свою функцию def fun(аргументы) и в ней этот код) - это будет решением 1-го задания. А если написать ещё одну такую же функцию (только вместо print сделать return) - получится решение 2-го задания.

2020-10-04 08:05 UTC, IlyaOrlov requested changes

2020-10-04 08:05 UTC, IlyaOrlov commented on Practice/Taigunov/Test3.py
> +    print(max(a,b))
Не хватает вызова функции, чтоб проверить, что она работает:
test(10, 20)
test(40, 30)

2020-10-04 09:02 UTC, taigunov commented on Practice/Taigunov/Test3.py
> +    print(max(a,b))
Ок

2020-10-04 09:40 UTC, IlyaOrlov approved these changes

2020-10-04 09:40 UTC, merged

2020-10-05 13:55 UTC, taigunov commented
Ок