Taigunov 1
IlyaOrlov/PythonCourse2 pull request #25
Opened 2020-10-05 11:55 UTC by taigunov

2020-10-05 18:56 UTC, IlyaOrlov requested changes

2020-10-05 18:56 UTC, IlyaOrlov commented on Practice/.idea/.gitignore
> +# Default ignored files
Удалите папку .idea, сделайте commit и push. Папка .idea не должна попадать в коммит.

2020-10-05 18:56 UTC, IlyaOrlov commented on Practice/Taigunov1/Task 2 from 2 Lec.py.py
> +def max (x=12, y=44):
Нельзя использовать имена встроенных функций для именования своих функций и переменных. Ваша функция называется так же, как встроенная функция, которую вы использовали в строке 3. Происходит перекрытие имен, и встроенная функция теперь уже будет недоступна.

2020-10-05 18:56 UTC, IlyaOrlov commented on Practice/Taigunov1/Task 3 Test Game.py
> +    persons[n]._runquickly(x**2)
runquickly() может только один из дочерних классов, поэтому данная строка вызовет ошибку для Person() и Person1(), если поправить код:
```python
persons = [Person(), Person1(), PersonFly()]
while True:
    for person in persons:
         person.draw()
         person._run()
    cmd = input("Взять (flower или mash):")
    n=int(input("Введите ID person(0-Person, 1-Person1, 2-PersonFly):"))
    if cmd == "flower":
        persons[n]._runquickly()
    elif cmd == "mash":
        persons[n]._run()
```
Требовалось только описать классы, но раз уж вы написали их обработку, то замечания будут и по ней.

2020-10-05 18:56 UTC, IlyaOrlov commented on Tasks/pep8task.py
>  from time import *
Общий файл задания - Tasks/pep8task.py менять не нужно. В этом файле надо вернуть все как было.

2020-10-12 09:16 UTC, IlyaOrlov commented on Practice/Taigunov1/Task2 from 4Lec.py
> +s=list(input('Введите пятизначное число  '))
В список преобразовывать не обязательно. Строка тоже поддерживает операцию индексирования ([]).

2020-10-12 09:19 UTC, IlyaOrlov requested changes

2020-10-12 09:19 UTC, IlyaOrlov commented on Practice/Taigunov1/Task2 from 4Lec.py
> +    print(f"{i} - элемент равен {s [i]}")
ОК. Только по заданию начать следует с 1, а не с 0. Для строки '12345'
1 элемент равен 1
2 элемент равен 2
и т.д.

2020-10-12 11:20 UTC, taigunov commented on Practice/Taigunov1/Task2 from 4Lec.py
> +s=list(input('Введите пятизначное число  '))
Ok.

2020-10-12 11:23 UTC, taigunov commented on Practice/Taigunov1/Task2 from 4Lec.py
> +    print(f"{i} - элемент равен {s [i]}")
Ok. Я сделал апдейт кода

2020-10-12 11:56 UTC, IlyaOrlov commented on Practice/Taigunov1/Task2 from 4Lec.py
> +    print(f"{i} - элемент равен {s [i]}")
Теперь он пропускает 0-й элемент, и для '12345' получается:
1 элемент равен 2
2 элемент равен 3
и т.д.

2020-10-14 19:09 UTC, IlyaOrlov approved these changes

2020-10-14 19:10 UTC, merged