Oxana m
IlyaOrlov/PythonCourse2 pull request #28
Opened 2020-10-07 17:58 UTC by Xanamas

change to task 1 and 2 - returning added. 
added classes for task 3 from HW

2020-10-07 20:16 UTC, IlyaOrlov commented on Practice/OxanaM/Game_empty_classes.py
> +        self.speed_run = value
Замечательно! Такой вопрос... Если у нас в зависимости от разной скорости должна быть разная анимация (ну т.е. одним значением скорости не обойтись: если мы вызываем run, когда скорость большая, печатается "Running fast", когда маленькая - "Running slowly", когда скорость очень большая - "Running very fast"), то как можно сделать поддержку для этой возможности? Подсказка: поля объекта могут хранить не только статические значения, но и указатели на функции. Например:
```python
def run1():
    print('running fast')

def run2():
    print('running slowly')

r = run1
r()  # напечатается running fast
r = run2
r()  # напечатается running slowly
```

2020-10-12 19:12 UTC, Xanamas commented on Practice/OxanaM/Game_empty_classes.py
> +        self.speed_run = value
я удалила данный файл и запушила на свою ветку.  Файл на ветке восстановила. могу я внести изменения в него?

2020-10-12 21:11 UTC, IlyaOrlov commented on Practice/OxanaM/Game_empty_classes.py
> +        self.speed_run = value
Да, конечно.

2020-10-12 21:19 UTC, IlyaOrlov requested changes

2020-10-12 21:19 UTC, IlyaOrlov commented on Practice/OxanaM/Les4_task_1.py
> +    if i % 3 == 0 and i % 5 != 0 and i % 15 != 0:
Проще сначала (в ветке if) проверить кратность 15, а в ветках elif - кратность 5 и 3. Будет меньше кода и меньше проверок.

2020-10-12 21:19 UTC, IlyaOrlov commented on Practice/OxanaM/Les4_task2.py
> +for i in str(number):
Есть нюанс... Выводить нужно не только цифру, но и ее порядковый номер в числе, начиная с 1, как в примере:
1 цифра равна 1
2 цифра равна 0
и т.д.

2020-10-13 21:22 UTC, merged