Task videogame
IlyaOrlov/PythonCourse2 pull request #29
Opened 2020-10-08 10:27 UTC by Irene-lab80

2020-10-08 12:52 UTC, IlyaOrlov commented on Practice/IrinaZ/task_3_videogame.py
> +    __health = 100
Почему health, shields и ammo вынесены в дочерние классы?

2020-10-08 13:00 UTC, IlyaOrlov commented on Practice/IrinaZ/task_3_videogame.py
> +    def run(self):  # метод, отвечающий за бег, public
Вопрос на понимание: как сделать так, чтоб персонажи могли бегать по-разному в зависимости от подобранной item? Например:
```python
Shooter1 = OffenceCharacters()
Shooter1.run()  # просто "Running"
Shooter1.collect_items('bonus')
Shooter1.run()  # теперь уже "Running fast"
```
Подсказка: переменные могут указывать не только на числа и строки, но и, например, на функции.
```python
def fun():
    print('hello')

f = fun  # это НЕ вызов функции
f()  # а это вызов: напечатается 'Hello'
```

2020-10-12 12:16 UTC, IlyaOrlov requested changes

2020-10-12 12:16 UTC, IlyaOrlov commented on Practice/IrinaZ/task_3_videogame.py
> +    __health = 100
\_\_health и health - это разные переменные. Надо определиться, сколько подчеркиваний использовать в именах данных атрибутов. Мы еще не проходили разницу между закрытыми (private) и защищенными (protected) атрибутами, поэтому пока в двух словах: два подчеркивания в начале - это закрытая переменная (скрывается не только от пользователей класса, но и от дочерних классов), одно подчеркивание в начале - это защищенная переменная (скрывается только от пользователей класса). Здесь, как я пониманию, health, ammo и т.д. должны быть доступны потомкам Characters, и эти потомки могут их переопределять. Поэтому везде (и в Characters и в его дочерних классах) стоит указать эти атрибуты как защищенные (с одним подчеркиванием в начале).

2020-10-12 12:24 UTC, Irene-lab80 commented on Practice/IrinaZ/task_3_videogame.py
> +    __health = 100
Ок, поняла. Исправлю.

2020-10-12 14:32 UTC, IlyaOrlov approved these changes

2020-10-12 14:32 UTC, merged