branch2asrequested
IlyaOrlov/PythonCourse2 pull request #33
Opened 2020-10-08 14:11 UTC by megavad

obj task

2020-10-08 20:45 UTC, IlyaOrlov submitted a review, later dismissed

2020-10-08 20:45 UTC, IlyaOrlov commented on Practice/VadikV/L3/main.py
> +    if cmd == "run":
Если установку скорости перенести в метод setspeed, то строки 17-25 заменяются тремя: 
```python
heroes[n].funct = getattr(heroes[n], cmd, None)
if heroes[n].funct is None:
    break 
```
В идеале же, как обсуждалось на лекции, вынести методы run, whoami, setspeed из класса Base в отдельную иерархию классов (например, Action).

2020-10-08 20:45 UTC, IlyaOrlov commented on Practice/VadikV/L3/base.py
> +        self.name = GivenName
Стоит задействовать родительский конструктор \_\_init\_\_ для установки self.name. Если есть возможность переиспользовать код - надо ей пользоваться. Тем более вместе с этой возможностью вы упускаете в дочернем классе инициализацию funct. Если, например, в строке 4 в main.py выполнить вроде бы безобидный код heroes[2].funct() - будет ошибка.
Одно из правил применения принципа наследования заключается в том, что дочерний класс должен уметь все то же, что и базовый, плюс еще немного больше (но ни в коем случае не меньше).

2020-10-08 20:50 UTC, IlyaOrlov requested changes

2020-10-08 20:50 UTC, IlyaOrlov commented on Practice/VadikV/L3/base.py
> +    _speed = 0
Зачем две скорости?

2020-10-08 20:50 UTC, IlyaOrlov commented on Practice/VadikV/L3/main.py
> +        setattr(heroes[n], 'speed', int(input("Введите скорость (от 0 до 100): ")))
Что нам дает использование setattr для speed, если такой атрибут и так есть у всех наследников Base, и ничего не мешает нам написать проще: heroes[n].speed = int(input("Введите скорость (от 0 до 100): ")

2020-10-14 09:23 UTC, megavad commented
хотелось g/setattr попробовать. Оверхед, но микроскоп(setattr) уже был готов для следующего гвоздя (после getattr).

2020-10-14 09:29 UTC, megavad commented on Practice/VadikV/L3/base.py
> +    _speed = 0
Если б я реализовал функцию run, в ней участвовала бы скорость текущая(_speed), а не запрошенная для объекта (speed). Извиняюсь, надо было более очевидную конвенцию для именования применить, и назвать не _speed, a speed_PV (processvalue), и не speed, a speed_SP (setpoint).

2020-10-14 14:46 UTC, megavad commented on Practice/VadikV/L3/main.py
> +    if cmd == "run":
вынес методы перемещения в дочерний класс, от которого создаю потом реальные классы

2020-10-14 15:53 UTC, IlyaOrlov commented on Practice/VadikV/L3/main.py
> +    if cmd == "run":
Зачем выносить методы перемещения в **дочерний** класс? В идеале вообще не стоит путать две сущности в одной иерархии? Нужен класс для персонажей, нужен класс (иерархия классов) для действий. Например:
```python
class Hero:
    action = None

class RunAction:
    def do_action():
        print('Simple run')

class FastRunAction(RunAction):
    def do_action():
        print('Fast run')

h = Hero()
h.action = RunAction()
h.action.do_action()  # Simple run
h.action = FastRunAction()
h.action.do_action()  # Fast run
```
Такое разделение обязанностей позволяет нам не менять код персонажа при необходимости как-то поменять анимацию того или иного действия.

2020-10-14 16:00 UTC, IlyaOrlov requested changes

2020-10-15 15:01 UTC, megavad commented on Practice/VadikV/L3/base.py
> +        while self.speed == 0:
UnboundLocalError: local variable 'speed' referenced before assignment если убрать self

2020-10-15 19:06 UTC, IlyaOrlov commented on Practice/VadikV/L3/base.py
> +        while self.speed == 0:
Так у вас до этого speed бралась из строки 4. Ничего не мешает вставить ее перед строкой 19?

2020-10-16 04:17 UTC, megavad commented on Practice/VadikV/L3/base.py
> +        while self.speed == 0:
Вся моя изначальная задумка изменилась. Я хотел, чтобы speed менялась в одном месте, а устанавливалась в другом. Потом зачем-то перенёс считывание запроса скорости input в SetSpeed, и идея стала окончательно разрушена. Но на подкорках speed ещё глобален.
Надо как-то сделать ещё, чтобы нельзя было создать объект класса Base.  Stackowerflow говорит, что надо скопипастить что-то типа     
def __new__(cls, GivenName, lbound, ubound):
        if cls is Base:
            raise TypeError("Should not be instantiate")
        return object.__new__(cls, GivenName, lbound, ubound)
но т.к. у меня производные классы определяются без параметров lbound и ubound, а new у базового 
и если я добавляю в производные классы
    def __new__(cls, GivenName):
        return object.__new__(cls)
то всё работает, но я не совсем понимаю - как (мы ж возвращаем __new__(cls) без GivenName). Просто посмотрел, чего хочет компилятор, и дал ему это.

2020-10-16 06:32 UTC, IlyaOrlov commented on Practice/VadikV/L3/base.py
> +        while self.speed == 0:
"Я хотел, чтобы speed менялась в одном месте, а устанавливалась в другом." - зачем? выглядит как усложнение. Чем больше возможностей (мест кода), чтоб изменить какой-либо параметр - тем сложнее контролировать программу. Если требовалось, чтоб скорость устанавливалась в одном месте, а использовалась в другом - у вас это реализовано с self._speed.
Если вы хотите, чтоб Base возглавлял иерархию классов, но нельзя было создать объект этого класса, то самый правильный способ - сделать класс (и какой-нибудь метод в нем) абстрактным:
```python
from abc import ABC, abstractmethod

class Base(ABC):
    ...
    @abstractmethod
    def __init__(self, GivenName, lbound, ubound):
        ...
```
Наследовать его можно, init в дочерних класса использовать можно, а создавать его экземпляры (инстанцировать этот класс) - нельзя.
Определяя \_\_new\_\_ в дочерних классах с return object.\_\_new\_\_(cls)  вы фактически создаете их в обход базового класса. Зачем их тогда наследовать от Base? Кстати, object.\_\_new\_\_(cls) - это базовый встроенный метод создания экземпляров классов, ему ничего кроме указателя на класс передавать не нужно.

2020-10-16 06:49 UTC, IlyaOrlov requested changes

2020-10-16 06:49 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +class FizzBuzzProvider:
ООП, конечно, хорошая парадигма, но ОПП ради ООП использовать не стоит. Достаточно сложно понять, что делает данный код, не вчитываясь в детали.

2020-10-16 06:49 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +        __counter = 1
Нижнее подчеркивание применяют, в частности, для скрытия полей экземпляров. В чем смысл двойного нижнего подчеркивания для безобидной локальной переменной?

2020-10-16 06:49 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +            print(i, "цифра равна", strNum[i])
По заданию нумерацию надо выводить, начиная с 1.

2020-10-16 06:49 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +        for i in range(len(strNum))[::]:
Зачем [::]?

2020-10-16 06:49 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +def sortArr(list):
list - это имя встроенного метода приведения к типу список. Не стоит его использовать для своих переменных и функций.
Аналогично - для min.

2020-10-16 06:49 UTC, IlyaOrlov commented on Practice/VadikV/L3/main.py
> +from base import *
Можно как-то избежать такой вариант импорта?

2020-10-16 09:06 UTC, megavad commented on Practice/VadikV/L4/FizzBuzz.py
> +        for i in range(len(strNum))[::]:
боян убрал,  экспериментировал - забыл убрать

2020-10-17 08:31 UTC, IlyaOrlov requested changes

2020-10-17 08:31 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +    if len(elemList) > 1: sortArr(elemList[1:])
В некоторых случаях рекурсия, конечно, позволяет упростить код... Но рекурсия подразумевает многократный вызов функции, при каждом вызове функции  происходит копирование аргументов, адресов возврата в стек, размер стека достаточно мал, и стек может быстро переполниться. Поэтому, если сортируемый список будет достаточно большим, рекурсия завершится досрочно с ошибкой из-за переполнения стека. Оптимальным вариантом здесь было бы применение еще одного цикла - это будет быстро и оптимально с точки зрения экономии памяти.

2020-10-17 08:31 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +    minElemList.append(minElem)
Если вместо firstElem запомнить индекс начального элемента, то вспомогательный список не понадобится. Достаточно менять местами элементы с индексами 'начальный' и idx. Если же вы все-таки хотите использовать вспомогательный список, стоит внести его внутрь sortArr (сделать локальной переменной), а потом возвращать из функции при помощи return. Это сделает функцию более самодостаточной, ею легко будет пользоваться, импортируя в другие файлы.

2020-10-18 13:04 UTC, megavad commented on Practice/VadikV/L4/FizzBuzz.py
> +    if len(elemList) > 1: sortArr(elemList[1:])
У нас 999 вызовов, и нет ограничений по условиям. Но ок, переписал на вложенные циклы, закоммичу с последними заданиями. У меня вопросы по ним:
4) передаётся на вход файл или строка - надо реализовать парсинг аргументов и в зависимости от - принимать имя файла или запрашивать строку?
5) пришлось гуглить, что интерполяция - не только усреднение значений. Вот будет строка
aabcabbcaabcс и словарь {"a" : "ab", "b" : "ac"}, в итоге результат зависит от того, в каком порядке будут применяться ключи словаря

2020-10-18 13:40 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +    if len(elemList) > 1: sortArr(elemList[1:])
Никто не говорит, что ваше решение неправильное. Оно просто неоптимальное. Кому нужно, чтоб задания проверялись только для галочки по критериям работает/не работает? Мне-то не жалко, могу, не глядя, approve ставить.
4) Можно написать две функции: одну для строк, другую - для файлов. При необходимости вторую можно реализовать через первую.
5) Конкретно про слово "интерполировать" в 5-м задании я говорил на лекции (см. 2:43:50 в записи). Да, желательно написать такой алгоритм, который бы не зависел от порядка применения ключей словаря.

2020-10-18 13:53 UTC, megavad commented on Practice/VadikV/L4/FizzBuzz.py
> +    if len(elemList) > 1: sortArr(elemList[1:])
Не понимаю пока, как сделать независимым от порядка применения. Ведь применение первого ключа порождает другие последовательности непосредственно в месте его применения. {а:ab, ac:bb} Если мы только не разобъём строку на словарные включения; но если мы разобъём сначала по включению "a" в строке "acba", и словаре будет ключ "ac", он уже не применится в том месте, т.к. по "a" было разбито раньше. Если вначале применим ключ "ac", потеряем первое включение "а"

2020-10-18 17:02 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +    if len(elemList) > 1: sortArr(elemList[1:])
Без дополнительных ограничений на шаблоны или на словарь обойтись не получится. Иначе, как вы правильно обнаружили, получается зацикливание в логике.
Как вариант - строго определиться с тем, что считать шаблоном. Например, набор букв, отделенный пробелом (слово) - это шаблон, а какая-либо отдельная буква в этом слове, или несколько слов - это не шаблон. Тогда мы можем разбить строку на список шаблонов (слов), идти по этому списку (а не по словарю) и заменять его элементы на значения из словаря.
Другой вариант: сделать список из ключей, отсортировать его от сложных ключей к простым (по длине ключа) и идти по этому списку.

2020-10-18 23:06 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +        tmpVal = elemList[i]
Можно так (без вспомогательной переменной):
elemList[i], elemList[minElemIdx] = elemList[minElemIdx], elemList[i]

2020-10-18 23:16 UTC, IlyaOrlov requested changes

2020-10-18 23:16 UTC, IlyaOrlov commented on Practice/VadikV/L4/FizzBuzz.py
> +dig = int(input("введ цифру"))
Ввел 3, но первый столбец не удалился (только третий).

2020-10-22 09:26 UTC, IlyaOrlov approved these changes
Все ОК. Только небольшое замечание: Resolve conversation должен нажимать тот, кто этот conversation начал (по открытым conversation я смотрю исправления замечаний).

2020-10-22 09:26 UTC, merged