tasks update
IlyaOrlov/PythonCourse2 pull request #34
Opened 2020-10-12 15:23 UTC by Irene-lab80

2020-10-12 21:32 UTC, IlyaOrlov requested changes

2020-10-12 21:32 UTC, IlyaOrlov commented on Practice/IrinaZ/4th_lecture_task_2.py
> +            return print(*args[i], sep='\n')
Оператор return осуществляет безусловный немедленный возврат из функции. Весь код после него (строка 15) выполнен не будет. С тем же успехом можно было просто написать print(*args[i], sep='\n') вместо строк 13-15. Но.. 
1) требовалось вывести цифры в определенном формате: 
1 цифра равна 1
2 цифра равна 0
и т.д.
2) return print(...) априори вернет None, поэтому такая запись выглядит странновато.
3) если убрать return - то не понадобится и разыменование аргументов (*). В new_line будет передан один аргумент - строка из input(), которая прекрасно поэлементно обходится в цикле.

2020-10-12 21:32 UTC, IlyaOrlov commented on Practice/IrinaZ/4th_lecture_task_3.py
> +        min_value = i
ОК. Только имя переменной немного не отражает ее сути. min_value - это же все-таки не сам минимальный элемент, а только индекс (номер) этого элемента в массиве (min_value_index).

2020-10-13 12:09 UTC, Irene-lab80 commented on Practice/IrinaZ/4th_lecture_task_2.py
> +            return print(*args[i], sep='\n')
1.  Не так поняла условие, переделаю.
2.  В каком смысле return print(...) вернет None? У меня все работало.
3.  Как тогда понять в какой функции надо что-то возвращать а в какой нет?

2020-10-13 12:36 UTC, IlyaOrlov commented on Practice/IrinaZ/4th_lecture_task_2.py
> +            return print(*args[i], sep='\n')
> 1. Не так поняла условие, переделаю.
> 2. В каком смысле return print(...) вернет None? У меня все работало.
> 3. Как тогда понять в какой функции надо что-то возвращать а в какой нет?

1. ОК.
2. Можно что-то вывести на экран с помощью print, можно что-то вернуть с помощью return, но объединять их в одном выражении не нужно.
3. Это вы сами решаете. По смыслу print - это просто печать результата на экран, **это не часть алгоритма**. Чаще всего с его помощью мы выводим какую-то вспомогательную информацию. return - это способ возврата из функции и передачи из нее какого-либо значения для последующего использования. Например:
```python
def fun(a, b):
    print(a, b)  # можно (но не обязательно) напечатать a и b, чтоб убедиться, что в функцию передаются правильные аргументы
    return a + b

res = fun(4, 5) * 10  # благодаря тому, что функция возвращает значение, мы можем подставить вызов этой функции в другой выражение
print(res)  # можно напечатать результат для наглядности

```

2020-10-14 15:24 UTC, IlyaOrlov approved these changes

2020-10-14 15:24 UTC, merged