прошу помочь с комментариями
IlyaOrlov/PythonCourse2 pull request #37
Opened 2020-10-12 23:11 UTC by n1kasus

2020-10-12 23:19 UTC, n1kasus commented
Я правильно понимаю, что пока вы не примите мой пул реквест в общую ветку на моем бранче krayukhin я буду видеть только те файлы которые были на мастере до создания бранча.
Т.о. чтобы сделать новое задание мне нужно перейти в мастер и создать новый бранч? 
А если я создам такую же папку и такие же файлы в новм бранче не будет ли накладок?

2020-10-13 07:34 UTC, IlyaOrlov commented
> Я правильно понимаю, что пока вы не примите мой пул реквест в общую ветку на моем бранче krayukhin я буду видеть только те файлы которые были на мастере до создания бранча.

То, что я пока не принял ваш пул реквест в общую ветку (master), не должно мешать вам подтягивать последние изменения в ваш бранч из этой общей ветки. Достаточно выполнить команду git pull origin master. Если потом еще сделаете git push, то эти изменения и в пул реквесте появятся.

> Т.о. чтобы сделать новое задание мне нужно перейти в мастер и создать новый бранч?
Совсем не обязательно.

> А если я создам такую же папку и такие же файлы в новм бранче не будет ли накладок?
Будут.

2020-10-13 07:40 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +p = BaseHero() #4. Здесь мы задаем переменной p класс BaseHero?
Когда указывается имя класса со скобками - это означает, что мы создаем экземпляр данного класса. Само описание класса (например, строки 1-8) - это как чертеж автомобиля, а экземпляр - это как сам автомобиль, построенный по этому чертежу. Аналогично определению и вызову функции.
Здесь мы создаем экземпляр класса BaseHero и привязываем p к этому экземпляру.

2020-10-13 07:45 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +p.action = Run() #5. Самый главный вопрос, что? как? что происходит? p меняется на BaseHero, ищется в BaseHero переменная action которой присвается класс Run?,
После выполнения строки 31 p указывает на экземпляр BaseHero. В данной строке мы обращаемся к некоторому полю action внутри экземпляра BaseHero и связываем это поле с экземпляром класса Run. Можно называть action и переменной, но термин переменная чаще используется для имен лежащих вне каких либо объектов (как? например, p), тогда как action принадлежит экземпляру BaseAction, поэтому action лучше называть полем или атрибутом экземпляра класса BaseAction.

2020-10-13 07:48 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +        p.action = FastRun()  #3. p.action = Run() меняется на FastRun&?
Да. Здесь p.action отвязывается от своего предыдущего значения и привязывается к FastRun(). То же самое если бы мы написали: x = 10, а потом х = 20. Только action принадлежит p, а вместо 10 и 20 здесь экземпляры классов.

2020-10-13 07:49 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +while True: #2. Вроде понятно как цикл срабатывает но вот логику p.action понять не могу
В самой p.action никаких чудес нет. Это просто несвободная переменная - поле p.

2020-10-13 07:50 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +class FastRun(Run): # 6 (Не факт что мысль правильная) этот класс подставляется вместо action в класс BaseHero
Только не вместо action, а вместо, например, Run().

2020-10-13 07:56 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +    p.action.run() #7. здесь мозг уже не может понять что за точка на точке, вызов метода run у подставленного циклом класса FastRun
"вызов метода run у подставленного циклом класса FastRun" - именно так (только не класса FastRun, а экземпляра класса FastRun, т.к. в строке 38 написано FastRun(); если б было написано просто FastRun - тогда речь бы шла о вызове метода класса).
Точка означает вложенность, не больше. Как в сказке: игла в яйце, яйцо в утке, утка в зайце.. На Python это запишется так: Заяц.Утка.Яйцо.Игла.

2020-10-13 08:02 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +#1. Не понимаю как вывести остальные классы и почему PC подчеркивает методы классов Hero и FlyHero (или классы бега выдают на принт только то что у них в классе?)
Остальные классы это FlyHero? Можно спросить у пользователя, кем он хочет управлять i = input(), если i == 'f', то все, что вы делали с p.action - надо сделать с a.action (a = FlyHero() в строке 33), если i == 'b', то выполняется код с p.action. Просто будет чуть больше if'ов.
PC подчеркивает эти методы, потому что они принимают аргумент self, но никак его не используют. Ошибки нет, но PC намекает, что надо объявить эти методы статическими (об статических методах мы еще поговорим на следующих лекциях).

2020-10-13 18:30 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +p.action = Run() #5. Самый главный вопрос, что? как? что происходит? p меняется на BaseHero, ищется в BaseHero переменная action которой присвается класс Run?,
Да. Только правильнее говорить: поле action становится **экземпляром** класса Run (или его дочерних классов) и у нас происходит некая вложенность **экземпляров** классов.
Иначе говоря, классы BaseHero и Run связываются через композицию (это способ связи альтернативный наследованию). Как вы могли заметить, связь через композицию гораздо более гибкая, чем через наследование, ее очень легко менять во время выполнения программы.

2020-10-14 06:38 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +    if FlyHero.f == 1: #Не факт что проверка правильная, но вроде работает)
А что здесь проверяется?

2020-10-14 06:45 UTC, IlyaOrlov requested changes

2020-10-14 06:45 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +    if FlyHero.f == 1: #Не факт что проверка правильная, но вроде работает)
Если вы хотите проверить, умеет ли p летать, прежде чем вызывать у него метод fly, то нужно сделать так, чтоб проверка эта касалась только p и не зависела от сторонних переменных (типа FlyHero). Вариант 1: добавить в BaseHero метод fly по умолчанию (с телом pass, метод как бы есть, но он пустой, т.к. BaseHero летать не умеет), тогда и проверка не понадобится. Вариант 2 (не особо изящный): if hasattr(p, 'fly')

2020-10-14 07:51 UTC, n1kasus commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +    if FlyHero.f == 1: #Не факт что проверка правильная, но вроде работает)
Хотел сделать по первому варианту, тогда вопрос: какой смысл от наследования если нам в родительском классе все равно приходится указывать новые методы дочерних (т.е. в дочернем без указания пустого метода в родительском мы не можем правильно вызвать)? Вариант 2 если честно я не совсем понимаю hasattr

2020-10-14 07:54 UTC, n1kasus commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +    if FlyHero.f == 1: #Не факт что проверка правильная, но вроде работает)
> А что здесь проверяется?
Проверяется есть ли метод fly и выводится, если есть, понимаю что по-турецки сделал, но это было сделано для исключения метода fly из родительского класса

2020-10-14 15:09 UTC, IlyaOrlov commented on Practice/Krayukhin_Konstantin/task 2/game.py
> +    if FlyHero.f == 1: #Не факт что проверка правильная, но вроде работает)
1. Новые методы нам нужно указывать в родительском классе, только если мы хотим одинаково обрабатывать всю иерархию классов (родительских, дочерних) - иначе говоря, для реализации полиморфизма. Наследование, напомню, нужно нам, чтоб не копировать код в дочерние классы.
2. hasattr(X, Y) - это просто встроенная функция, которая смотрит на экземпляр X (с учетом его класса) и ищет в нем метод с именем Y.

2020-10-15 08:45 UTC, IlyaOrlov approved these changes

2020-10-15 08:45 UTC, merged