Teterin Roman added exercise 1 - 3 for lesson 2
IlyaOrlov/PythonCourse2 pull request #41
Opened 2020-10-15 14:22 UTC by rateterin

2020-10-15 21:20 UTC, IlyaOrlov requested changes

2020-10-15 21:20 UTC, IlyaOrlov commented on Practice/Teterin_Roman/lesson-4/Ex-3.py
> +        arr[i], arr[arr.index(min(arr[i + 1:]), i + 1)] = \
Получилось, конечно, компактно, но arr[arr.index(min(arr[i + 1:]) фактически вычисляется дважды, что не оптимально. Лучше запомнить индекс в отдельную переменную. Также нужно иметь в виду, что мы здесь каждый раз сначала бежим по списку, когда ищем минимальный элемент, а потом бежим еще раз к этому же элементу, когда определяем его индекс. Самописный цикл поиска позволил бы ускорить работу вдвое.

2020-10-15 21:20 UTC, IlyaOrlov commented on Practice/Teterin_Roman/lesson-4/Ex-3.py
> +for i, el in enumerate(arr):
Если el не нужен,  а for использовать хочется, то лучше так:
```python
for i in range(len(arr)):
```

2020-10-15 21:20 UTC, IlyaOrlov commented on Practice/Teterin_Roman/lesson-4/Ex-1.py
> +    print(('', 'Fizz')[num % 3 == 0] + ('', 'Buzz')[num % 5 == 0] + ('', str(num))[num % 3 != 0 and num % 5 != 0],
Оригинально, но (возможно, это мое субъективное мнение) не очень читабельно.
Лучше так (как вариант):
```python
for num in range(1, 101):
    print(('', 'Fizz')[num % 3 == 0] +
          ('', 'Buzz')[num % 5 == 0] +
          ('', str(num))[num % 3 != 0 and num % 5 != 0],
          end=' ')
```

2020-10-21 21:04 UTC, rateterin commented on Practice/Teterin_Roman/lesson-4/Ex-3.py
> +        arr[i], arr[arr.index(min(arr[i + 1:]), i + 1)] = \
Согласен, спасибо за комментарии, убежал исправлять...

2020-10-21 21:10 UTC, rateterin commented on Practice/Teterin_Roman/lesson-4/Ex-3.py
> +for i, el in enumerate(arr):
Осознал, уже правлю..

2020-10-21 21:11 UTC, rateterin commented on Practice/Teterin_Roman/lesson-4/Ex-1.py
> +    print(('', 'Fizz')[num % 3 == 0] + ('', 'Buzz')[num % 5 == 0] + ('', str(num))[num % 3 != 0 and num % 5 != 0],
Да, супер, всегда так буду делать, сейчас поправлю!!!

2020-10-21 21:19 UTC, rateterin reviewed
Внес правки.

2020-10-22 09:17 UTC, IlyaOrlov commented on Practice/Teterin_Roman/lesson-4/Ex-3.py
> +for i in range(len(arr)):
Чтоб стало идеально, осталось объединить строки 19 и 20 в 
```python
for i in range(len(arr) - 1):
```

2020-10-22 09:32 UTC, rateterin commented on Practice/Teterin_Roman/lesson-4/Ex-3.py
> +for i in range(len(arr)):
)))) ну ё маё, точно)

2020-10-22 09:35 UTC, rateterin reviewed
Объединил строки 19 и 20)

2020-10-22 09:58 UTC, IlyaOrlov approved these changes

2020-10-22 09:59 UTC, merged