Tasks from 4 lecture
IlyaOrlov/PythonCourse2 pull request #44
Opened 2020-10-18 18:37 UTC by taigunov

2020-10-18 23:35 UTC, IlyaOrlov requested changes

2020-10-18 23:35 UTC, IlyaOrlov commented on Practice/Taigunov2/Task5 from 4 lec..py
> +print (str.replace("весною", "осенью"))
Пары "весною": "осенью" и т.д. надо поместить в словарь и замену провести по этому словарю. Кстати, наверное, подразумевалось не str.replace, а s.replace.

2020-10-18 23:35 UTC, IlyaOrlov commented on Practice/Taigunov2/Task4 from 4 lec.py
> +tab = s.expandtabs(tabsize=4)
Еще надо предусмотреть замену пробелов на табуляцию (символ табуляции - '\t'). И лучше оформить это в виде своей функции. Кстати, для обоих видов преобразований вам пригодился бы строковый метод replace.

2020-10-18 23:35 UTC, IlyaOrlov commented on Practice/Taigunov2/Task 6 from 4Lec.py
> +matrix = np.delete(matrix, 0, 1)
Нужно удалить столбцы, содержащие заданную цифру. Например, в матрице (в Python ее можно представить, как список из списков) 
```python
m = [
    [1, 2, 3], 
    [3, 2, 1]
] 
```
удаляем столбцы с цифрой 3. Остается средний столбец:
```python
 m = [
    [2], 
    [2]
]
```

2020-10-19 06:26 UTC, taigunov commented on Practice/Taigunov2/Task5 from 4 lec..py
> +print (str.replace("весною", "осенью"))
Хорошо. Буду пробовать

2020-10-20 17:33 UTC, IlyaOrlov commented on Practice/Taigunov2/Task5 from 4 lec(upd).py
> +    txt = txt.replace(key, str(dic[key]))
dic[key] у вас и так строка (в словаре же у вас все значения - строки), поэтому преобразовывать дополнительно в str необязательно.

2020-10-20 18:23 UTC, taigunov commented on Practice/Taigunov2/Task5 from 4 lec(upd).py
> +    txt = txt.replace(key, str(dic[key]))
Ok. Доделаю

2020-10-20 18:24 UTC, taigunov commented on Practice/Taigunov2/Task4 from 4 lec (upd).py
> +if cmd == "tab":
Ок. Буду дорабатывать.

2020-10-21 10:10 UTC, IlyaOrlov commented
Остался вопрос по Task 6 from 4Lec.py
Ну и старые версии решений (Task4 from 4 lec..py, Task5 from 4 lec..py) тоже, наверное, можно удалить (удалить файлы локально -> git rm 'имя_файла' -> git commit -m 'rm file' -> git push)

2020-10-28 12:23 UTC, merged