Taigunov patch 4
IlyaOrlov/PythonCourse2 pull request #50
Opened 2020-10-26 05:29 UTC by taigunov

2020-10-26 17:43 UTC, IlyaOrlov requested changes

2020-10-26 17:43 UTC, IlyaOrlov commented on Practice/Taigunov2/classPupil.py
> +class Pupil:
Pupil делает и в init, и в solve_task почти то же самое, что и Man. Стоит унаследовать Pupil от Man и переписать init и solve_task через вызовы super().\_\_init\_\_() и super().solve_task()

2020-10-27 15:34 UTC, IlyaOrlov requested changes

2020-10-27 15:34 UTC, IlyaOrlov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).__init__(name)
В python3 достаточно написать super().\_\_init\_\_(name). Аналогично в строке 23.
Код self.name = name в стр.20 писать не нужно, т.к. из-за вызова super().\_\_init\_\_(name) выполнится код в строке 6.

2020-10-27 15:34 UTC, IlyaOrlov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).solve_task()
ОК. Только задание он должен сделать не до, а после того, как поспит.

2020-10-27 18:21 UTC, taigunov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).__init__(name)
Ок. Я Вас понял. Мне PyCharm после того когда написал функцию super, сам автоматически ввел 
(Pupil, self).__init__(name). Огромное спасибо за замечание и разъяснение.

2020-10-27 18:39 UTC, taigunov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).solve_task()
Я Вас не совсем понял. Надо сначала измерить производительность функции перф-каунтром, а потом запустить рандомный тайм -слип ?

2020-10-27 19:42 UTC, IlyaOrlov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).solve_task()
Нет. Просто выполнить вызов super().solve_task() уже после time.sleep(n). Как по условию задачи требуется.

2020-10-27 19:44 UTC, IlyaOrlov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).__init__(name)
Странно, а у вас точно python 3 установлен, не python 2? Можно в командной строке выполнить команду python - и увидите версию.

2020-10-28 05:15 UTC, taigunov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).__init__(name)
В командной строке показал Python 3.8.6 может какой то баг? Но как Вы сказали все работает и гораздо легче и понятнее.

2020-10-28 05:18 UTC, taigunov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).solve_task()
Ok.

2020-10-28 12:23 UTC, IlyaOrlov commented on Practice/Taigunov2/classMAN&PUPIL.py
> +        super(Pupil, self).__init__(name)
Интересно. Ну это не баг, но возможно какой-то нюанс настройки PyCharm.

2020-10-28 12:23 UTC, IlyaOrlov approved these changes

2020-10-28 12:23 UTC, merged