Add files via upload
IlyaOrlov/PythonCourse2 pull request #51
Opened 2020-10-26 06:29 UTC by Zgura

2020-10-26 17:48 UTC, IlyaOrlov commented
Неплохо. Теперь бы еще Pupil реализовать.

2020-10-27 15:31 UTC, IlyaOrlov requested changes

2020-10-27 15:31 UTC, IlyaOrlov commented on Practice/Zgura/zgura_13_class_Pupil_(zaderzhka).py
> +class Pupil:
Хорошо бы Pupil от Man унаследовать: init у них почти одинаковый, solve_task - тоже.. почти.

2020-10-27 23:00 UTC, IlyaOrlov commented on Practice/Zgura/zgura_13_class_Pupil_(zaderzhka).py
> +        print("I'm not ready yet")
А здесь вот тоже super() по смыслу просится. Конкретно в 12-ю строку.

2020-10-28 06:58 UTC, Zgura commented on Practice/Zgura/zgura_13_class_Pupil_(zaderzhka).py
> +        print("I'm not ready yet")
Не понимаю для чего надо добавлять super() в 12 строку??? тем более, что там у меня функция print сидит. Или print надо будет сдвинуть вниз, а на 12 строке написать что-то типа super().solve_task()???
Но разве метод solve_task  уже не переопределён в моём случае? Я думал, что выдача метода solve_task зависит от того какой объект его вызывает, специально даже импортировал man_1 из родительского класса, чтобы проверить как solve_task будет по-разному работать ? Прошу объяснить... не понял куда и как ещё надо "присобачить" super(), код ошибок не выдаёт и вроде бы всё работает.

2020-10-28 12:36 UTC, IlyaOrlov commented on Practice/Zgura/zgura_13_class_Pupil_(zaderzhka).py
> +        print("I'm not ready yet")
В том, как написано сейчас, ошибки нет. Но по принципам ООП данное решение неоптимально. И вот почему.
Код в строке 12 в данном файле совпадает с кодом в строке 7 zgura_12_class_Man.py. Это неспроста. Подразумевается, что Pupil, как дочерний класс, должен расширять возможности базового (он делает то же самое и еще немножко). В общем случае, конечно, мы не можем предугадать на 100% какие особенности еще надо будет добавить в Pupil, но пока мы можем переиспользовать код базового класса, мы должны это делать.
Поэтому я и призываю вместо  дублирования кода print("I'm not ready yet"), вызвать  super().solve_task().
Если потребуется вместо "I'm not ready yet" выводить "I'm ready", то нам понадобится менять код только в одном месте - в методе solve_task базового класса, и для всех потомков это изменения применится само собой.

2020-10-28 12:39 UTC, IlyaOrlov commented on Practice/Zgura/zgura_13_class_Pupil_(zaderzhka).py
> +        print("I'm not ready yet")
Для пример... вот такой вариант:
```python
def fun1():
    print('Hello')

def fun2():
    print('Hello')
    print('Bye')
```
менее устойчив к изменениям (менее гибкий), чем такой
```python
def fun1():
    print('Hello')

def fun2():
    fun1()
    print('Bye')
```

2020-10-28 12:52 UTC, Zgura commented on Practice/Zgura/zgura_13_class_Pupil_(zaderzhka).py
> +        print("I'm not ready yet")
Всё понял, решение поправил!

2020-10-28 17:53 UTC, IlyaOrlov approved these changes

2020-10-28 17:53 UTC, merged