Zgura 001
IlyaOrlov/PythonCourse2 pull request #6
Opened 2020-09-24 15:13 UTC by Zgura

2020-09-24 18:20 UTC, IlyaOrlov requested changes

2020-09-24 18:20 UTC, IlyaOrlov commented on Practice/Zgura/zgura_01.py
> +print('Введите X1')
Здесь и ниже можно проще:
```python
a = input('Введите X1 ')
```

2020-09-24 21:57 UTC, Zgura commented
Понял. Есть уточняющий вопрос: после Х1 обязательно пробел ставить или нет ?
Вроде работает и без пробела в конце. Это опечатка или правила оформления?

С уважением, Владимир Згура
89200080680

  24.09.2020, 21:21, IlyaOrlov <notifications@github.com>


  @IlyaOrlov requested changes on this pull request.

  ----------------------------------------------------------------------------

  In Practice/Zgura/zgura_01.py:

  > @@ -0,0 +1,12 @@
  
  +print('Введите X1')


  Здесь и ниже можно проще:

  a     =     input  (  'Введите X1 '  )

  —
  You are receiving this because you authored the thread.
  Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-25 06:48 UTC, IlyaOrlov commented
> Понял. Есть уточняющий вопрос: после Х1 обязательно пробел ставить или нет ? Вроде работает и без пробела в конце. Это опечатка или правила оформления? С уважением, Владимир Згура 89200080680 24.09.2020, 21:21, IlyaOrlov <notifications@github.com> @IlyaOrlov requested changes on this pull request.
> […](#)
> ---------------------------------------------------------------------------- In Practice/Zgura/zgura_01.py: @@ -0,0 +1,12 @@ +print('Введите X1') Здесь и ниже можно проще: a = input ( 'Введите X1 ' ) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Пробел - это чтоб текст "Введите X1" визуально отделялся от того, что введет пользователь: **ВведитеX150** vs **ВведитеX1 50** Так-то в кавычках можно что угодно писать. Я б еще и двоеточие добавил: "Введите X1: "

2020-09-25 06:51 UTC, Zgura commented
понял, спасибо

  25.09.2020, 09:49, IlyaOrlov <notifications@github.com>

    Понял. Есть уточняющий вопрос: после Х1 обязательно пробел ставить или
    нет ? Вроде работает и без пробела в конце. Это опечатка или правила
    оформления? С уважением, Владимир Згура 89200080680 24.09.2020, 21:21,
    IlyaOrlov notifications@github.com @IlyaOrlov requested changes on this
    pull request.
    …
    ----------------------------------------------------------------------------
    In Practice/Zgura/zgura_01.py: @@ -0,0 +1,12 @@ +print('Введите X1')
    Здесь и ниже можно проще: a = input ( 'Введите X1 ' ) — You are receiving
    this because you authored the thread. Reply to this email directly, view
    it on GitHub, or unsubscribe.

  Пробел - это чтоб текст "Введите X1" визуально отделялся от того, что введет
  пользователь: ВведитеX150 vs ВведитеX1 50 Так-то в кавычках можно что угодно
  писать. Я б еще и двоеточие добавил: "Введите X1: "

  —
  You are receiving this because you authored the thread.
  Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-29 22:04 UTC, IlyaOrlov commented on Practice/Zgura/zgura_02.py
> +    else: print (b)
Отдельные выражения надо писать на отдельных строках.

2020-09-29 22:09 UTC, Zgura commented on Practice/Zgura/zgura_02.py
> +    else: print (b)
Не понял ) Прошу пояснить ) Что конкретно надо перенести на отдельные строки и почему ) ?

2020-09-29 22:33 UTC, IlyaOrlov commented on Practice/Zgura/zgura_02.py
> +    else: print (b)
Выражения if .. else и print - это разные выражения. Согласно PEP8 их нужно писать на разных строках, т.е. должно быть так:
```python
else:
    print(b)
```
См. слайд 14 в лекции ("оставлять несколько инструкций на одной строке не рекомендуется") и оригинал PEP8 https://www.python.org/dev/peps/pep-0008/#id28 (вот этот пункт с примерами "While sometimes it's okay to put an if/for/while with a small body on the same line, never do this for multi-clause statements. Also avoid folding such long lines!").

2020-09-29 22:48 UTC, Zgura commented on Practice/Zgura/zgura_02.py
> +    else: print (b)
Опять же... в чём тут физический смысл ) ? Почему желательно писать разные выражения на разных строках ? Это в конечном итоге как-то сказывается на быстродействии Питона ?

2020-09-29 23:00 UTC, IlyaOrlov commented on Practice/Zgura/zgura_02.py
> +    else: print (b)
На быстродействии Питона не сказывается. Но несоблюдение стиля сказывается на быстродействии разработчика, особенно когда приходится разбирать и поддерживать чужой код написанный вкривь и вкось. Можно строить здание ровненько и по правилам, а можно просто кирпичи один на другой накидать, и потом все подпорками обставлять, чтоб не падало.

2020-09-30 06:45 UTC, IlyaOrlov approved these changes

2020-09-30 06:45 UTC, merged