Teterin Roman added exercises 1-3 for lesson 5
IlyaOrlov/PythonCourse2 pull request #61
Opened 2020-11-05 21:27 UTC by rateterin

2020-11-06 20:25 UTC, IlyaOrlov requested changes

2020-11-06 20:25 UTC, IlyaOrlov commented on Practice/Teterin_Roman/lesson-5/Ex-3.py
> +            return str(e)
В целом все ОК, но возврат исключения как строки несколько смущает, т.к. извне не получится различить: то ли это исключение, то ли действительно такой текст был в файле.
Лучше исключение здесь просто выводить на экран (как в setter и deleter), а возвращать, например, None.

2020-11-09 11:40 UTC, rateterin commented on Practice/Teterin_Roman/lesson-5/Ex-3.py
> +            return str(e)
Спасибо, убежал фиксить..

2020-11-09 18:10 UTC, IlyaOrlov approved these changes

2020-11-09 18:10 UTC, merged