Add files via upload
IlyaOrlov/PythonCourse2 pull request #62
Opened 2020-11-05 22:44 UTC by Zgura

Добавил несколько комментариев  и пару вопросов в самом коде. Прошу обратить внимание )

2020-11-06 20:51 UTC, IlyaOrlov requested changes

2020-11-06 20:51 UTC, IlyaOrlov commented on Practice/Zgura/zgura_14_property.py
> +# Единственное, что не могу понять - почему у меня после File doesn't exist появляется None. Как от него избавиться?
В 28-й строке вы выводите на экран результат работы функции def content(self) (которая геттер, стр. 10). Эта функция, если файл существует, возвращает его содержимое (стр. 13). Что же возвращает эта функция, в случае если сработает Except? 
Кстати, в строке 14 следует отлавливать не все исключения, а только один конкретный тип.

2020-11-06 20:51 UTC, IlyaOrlov commented on Practice/Zgura/zgura_14_property.py
> +        f.write(string.encode())
А зачем encode()? Можно же сохранить строку как обычный текст. Лишние символы при чтении будут легко отбрасываться строковыми методами типа strip().

2020-11-06 20:51 UTC, IlyaOrlov commented on Practice/Zgura/zgura_14_property.py
> +# Этот вариант имеет место быть ? Надо ли расписывать все варианты except?  Чем этот вариант хуже ?
А в чем смысл функции, которая записывает что-то в файл и сразу читает и возвращает его содержимое?
Для сравнения:
- если вы собираетесь куда-то идти, то можете на случай жажды налить воду в бутылку и взять эту бутылку с собой: вы сможете попить когда захотите (аналогия с классом WrapToStr);
- если вы собираетесь куда-то идти, то на случай жажды вы наливаете воду в бутылку и... тут же ее всю выпиваете (аналогия с вашей функцией);

Класс WrapStrToFile позволяет кэшировать данные в файле, что удобно, например, при получении больших данных по сети (не все может влезть в память). В одном месте программы мы загрузили данные в файл и в любом другом месте программы мы можем эти данные считать. При этом в оперативной памяти мы ничего не храним, однако обращаться к полученным данным, пользуясь классом WrapStrToFile нам так же легко, как если бы мы работали с обычной переменной, указывающей на объект строкового типа в памяти.
Более того, если между получением данных и их использованием случится что-то непредвиденное, и программа аварийно завершит работу, данные никуда не пропадут, и мы сможем их считать после перезапуска.

2020-11-06 22:34 UTC, Zgura commented on Practice/Zgura/zgura_14_property.py
> +# Единственное, что не могу понять - почему у меня после File doesn't exist появляется None. Как от него избавиться?
Попробовал после except вместо print() написать pass... None всё равно появляется ))) Его возвращает функции def content(self) (которая геттер) в случае срабатывания  except... Возвращает ноль, ничего )) Понятно теперь.
Если не использовать try/except , то при запуске кода можно увидеть ошибку, которую можно отловить, она называется FileNotFoundError. Поправил в коде. Но заодно вопрос... на сколько это критично ? Чем чреват отлов всех исключений ?

2020-11-06 22:39 UTC, Zgura commented on Practice/Zgura/zgura_14_property.py
> +        f.write(string.encode())
со strip() сложнее было разобраться, чем с encode(), поэтому так и сделал ) Но теперь обязательно покопаюсь глубже...

2020-11-06 22:41 UTC, Zgura commented on Practice/Zgura/zgura_14_property.py
> +# Этот вариант имеет место быть ? Надо ли расписывать все варианты except?  Чем этот вариант хуже ?
Сравнение очень доходчивое.... так что удалил я функцию zapiska от греха подальше )) Эксперимент не удался )

2020-11-06 23:42 UTC, Zgura commented on Practice/Zgura/zgura_14_property.py
> +        f.write(string.encode())
Я что-то тут не понял... "отсеять лишние симвовы при выводе print" используя .decode() - я всего лишь хотел, чтобы ушли символы b' ' после вывода print... т.е. если не делать .decode(), то вывод будет в байтовом виде. В байтовом виде строка потому что я сделал f.write(string.encode()), т.е. при записи строки в файл перевёл её в байтовый вид... без этой манипуляции функция не работала.... 
 .strip() работает только со строками, но не с байтами... У меня каша в голове, объясните пожалуйста как можно было обойтись без encode/decode в моей функции... закину её в комментарий, т.к. в коде я её уже удалил и подгрузил без неё.
```python
import tempfile


def zapiska(string):
    f = tempfile.NamedTemporaryFile()
    try:
        f.write(string.encode())
    except:
        print("введите строковое значение")
    f.seek(0)  # Условно как будто переводим каретку печатной машинки в ноль для того, чтобы потом прочитать то,
    # что записали, иначе чтение будет происходить с текущей позиции
    print(f.read().decode())  # надо добавлять .decode() -  отсеять лишние симловы при выводе print

    f.close()

zapiska("www")
```

2020-11-07 20:59 UTC, IlyaOrlov commented on Practice/Zgura/zgura_14_property.py
> +        f.write(string.encode())
Если посмотреть на определение NamedTemporary файл, а точнее на сигнатуру этой функции: **tempfile.NamedTemporaryFile(mode='w+b', buffering=-1, encoding=None, newline=None, suffix=None, prefix=None, dir=None, delete=True, *, errors=None)**, то можно обратить внимание, что режим открытия файла по умолчанию 'w+b', т.е. на запись/чтение в бинарном виде. Поэтому f.write и не срабатывает для обычной строки. Также как и с обычным файлом. Если указать текстовый режим (например, **f = tempfile.NamedTemporaryFile(mode='w+t')**), то и encode/decode не нужны.

2020-11-07 21:24 UTC, IlyaOrlov commented on Practice/Zgura/zgura_14_property.py
> +# Единственное, что не могу понять - почему у меня после File doesn't exist появляется None. Как от него избавиться?
Отловить исключение и ничего с ним не сделать - это нехорошо. Замалчивание ошибок может привести к непонятному поведению программы. Лучше напечатать ошибку в геттере (print("File doesn't exist")) и ЯВНО вернуть None (явно, чтоб было понятно, что вы и собирались вернуть None в случае exception, а не просто забыли про возврат из функции в этом случае).
Опасен не отлов всех исключений, а потеря информации об исключениях. Если на любое исключение, особенно если оно связано не с существованием файла, а, например, с какими-либо проблемами при чтении, выводить "File doesn't exist", то это очень затруднит поиск причины ошибки для пользователя вашего кода.
В идеале для отдельных типов исключений должны быть отдельные обработчики, но предусмотреть все невозможно. Поэтому, исключение FileNotFoundError, которое мы знаем, как обработать (об этом сказано в условии задачи), мы отлавливаем и обрабатываем отдельно. Остальные исключения можно отловить через **except Exception as ex**, и при этом нужно напечатать (через print) информацию об этом исключении **ex**. Тогда и программа не упадет, и информация об ошибке не потеряется.
Однако отлавливать все исключения, предотвращая падение программы, стоит не всегда. Например, я запустил программу записи видеоконференции, а файл для сохранения записи открыть не удалось. Если программа записи, несмотря на это, продолжит работать (делать вид, что работает), то о проблеме я узнаю, только когда видеоконференция закончится, и я увижу, что у меня ничего не записалось (и будет уже поздно что-то предпринимать).

2020-11-08 15:27 UTC, Zgura commented on Practice/Zgura/zgura_14_property.py
> +        f.write(string.encode())
теперь всё понятно!

2020-11-08 15:30 UTC, Zgura commented on Practice/Zgura/zgura_14_property.py
> +        f.write(string.encode())
Теперь и необходимость в .strip() сама собой отпала!

2020-11-18 15:11 UTC, IlyaOrlov approved these changes

2020-11-18 15:12 UTC, merged