Add files via upload
IlyaOrlov/PythonCourse2 pull request #65
Opened 2020-11-09 14:44 UTC by Xanamas

Tasks 1,2,3 Lec 7

2020-11-09 16:35 UTC, IlyaOrlov requested changes

2020-11-09 16:35 UTC, IlyaOrlov commented on Practice/OxanaM/Lec7_task_1.py
> +def my_day_count(date_1, date_2):
**Рабочих** дней!!! Т.е. надо еще исключить субботы и воскресенья.

2020-11-12 10:26 UTC, Xanamas commented on Practice/OxanaM/Lec7_task_1.py
> +def my_day_count(date_1, date_2):
Переделала задание. Сделала включительно начальную и конечные даты. если надо строго между, без ключительно - переделаю

2020-11-12 18:49 UTC, IlyaOrlov commented on Practice/OxanaM/Lec7_task_1.py
> +def my_day_count(date_1, date_2):
Это непринципиально. 
Можно было просто проверять, что .isoweekday() < 6
Похоже часть кода потерялась (в конце файла diff = my_day_)

2020-11-16 14:11 UTC, Xanamas commented on Practice/OxanaM/Lec7_task_1.py
> +def my_day_count(date_1, date_2):
задание переделано, но не нахожу где еще раз push request сделать

2020-11-16 15:52 UTC, IlyaOrlov requested changes

2020-11-16 15:52 UTC, IlyaOrlov commented on Practice/OxanaM/Lec_8_part_3.py
> +    if b is None:
А если я его вызову как my_range(10), желая получить список элементов от 0 до 10?

2020-11-16 15:52 UTC, IlyaOrlov commented on Practice/OxanaM/Lec7_task_1.py
> +def my_day_count(date_1, date_2):
ОК. А зачем еще раз push request делать?

2020-11-16 17:24 UTC, Xanamas commented on Practice/OxanaM/Lec7_task_1.py
> +def my_day_count(date_1, date_2):
я подгрузила еще один файл.

2020-11-16 17:29 UTC, IlyaOrlov commented on Practice/OxanaM/Lec7_task_1.py
> +def my_day_count(date_1, date_2):
ОК

2020-11-17 07:17 UTC, Xanamas commented on Practice/OxanaM/Lec_8_part_3.py
> +    if b is None:
Внесла изменения

2020-11-17 08:35 UTC, IlyaOrlov approved these changes

2020-11-17 08:35 UTC, merged