Branch2asrequested
IlyaOrlov/PythonCourse2 pull request #67
Opened 2020-11-10 14:25 UTC by megavad

2020-11-10 16:13 UTC, IlyaOrlov requested changes

2020-11-10 16:13 UTC, IlyaOrlov commented on Practice/VadikV/L7/workDays.py
> +        yield 1 if (startDate+dt.timedelta(i)).weekday()<5 else 0
OK. Только yield для 0 делать, наверное, излишне.

2020-11-16 10:26 UTC, megavad commented on Practice/VadikV/L7/workDays.py
> +        yield 1 if (startDate+dt.timedelta(i)).weekday()<5 else 0
поправил

2020-11-16 15:40 UTC, IlyaOrlov requested changes

2020-11-16 15:40 UTC, IlyaOrlov commented on Practice/VadikV/L8/main.py
> +        raise ZeroDivisionError
А почему в этом случае именно такой тип исключения? Вроде никакого деления здесь не наблюдается.

2020-11-16 15:40 UTC, IlyaOrlov commented on Practice/VadikV/L8/main.py
> +    try:
Ловить исключения в задании не требовалось, поэтому можно было проще:
```python
    with open(source, 'r') as src:
        with open(destination, 'x') as dst:
            dst.writelines(src.readlines())
```

2020-11-16 15:40 UTC, IlyaOrlov commented on Practice/VadikV/L8/task10.py
> +        return str(self._round + other._round) + "," + str(tmpsum).zfill(3)
Сложение подразумевает возможность многократного повторения. Например, 
h=Money()
h1=Money()
h2=Money()
Сработает ли код: s = h + h1 +h2? По идее, должен. То же самое и для других операций.

2020-11-16 19:57 UTC, megavad commented on Practice/VadikV/L8/main.py
> +        raise ZeroDivisionError
InfiniteLoop появился позже, до этого математически кол-во шагов -> бесконечность, как при делении на 0
Объединил условия для вызова исключения InfiniteLoop

2020-11-16 21:28 UTC, megavad commented on Practice/VadikV/L8/main.py
> +    try:
прочитал про eXclusive creation, попробовал, работает, но при существующем destination в виде папки  FileExistsError: [Errno 17] File exists: 'd' вместо информировании о том, что это папка.

2020-11-16 21:28 UTC, megavad commented on Practice/VadikV/L8/task10.py
> +        return str(self._round + other._round) + "," + str(tmpsum).zfill(3)
сделал, после реализации инициализации с помощью копеек это оказалось весьма несложно

2020-11-17 08:47 UTC, IlyaOrlov commented on Practice/VadikV/L8/task10.py
> +        return str(self._round + other._round) + "," + str(tmpsum).zfill(3)
Да. Основная идея здесь в том, что результат операции должен иметь тот же тип, что и операнды: при сложении двух чисел получается число, при сложении двух строк - строка, при сложении экземпляров Money - экземпляр Money.

2020-11-17 08:55 UTC, IlyaOrlov commented on Practice/VadikV/L8/main.py
> +        return
В 36-й и в 39-й строках return явно лишний

2020-11-17 08:55 UTC, IlyaOrlov commented on Practice/VadikV/L8/main.py
> +    try:
Да, пожалуй, этот вариант не столь информативен, но проблему все же предотвращает.

2020-11-17 08:59 UTC, megavad commented on Practice/VadikV/L8/main.py
> +    try:
А под windows можно создать папку с таким же именем, как файл (или наоборот). Теперь понятна суть проблемы. Я тестирую свой код на mac os, поэтому же и в задаче с subprocess проверяю результат команды на posix, cmd = "cat" if "posix" in os.name else "type"

2020-11-17 09:40 UTC, IlyaOrlov commented on Practice/VadikV/L8/main.py
> +    try:
Нет, windows такого тоже не позволяет. Тут выбор решения зависит от того, что требуется в задаче.
Да, проверка os.name - это хорошая идея)

2020-11-17 11:25 UTC, megavad commented on Practice/VadikV/L8/main.py
> +        return
варнинги отревьюены и (кроме re.sub("\\" + r, т.к. не работает при re.sub("{1}", воспринимает как выражение) исправлены

2020-11-17 11:38 UTC, megavad commented on Practice/VadikV/L8/task10.py
> +        return str(self._round + other._round) + "," + str(tmpsum).zfill(3)
а так же при делении экземпляров - число, при делении экземпляра на число - экземпляр
почему-то мне не пришло изначально в голову, что будут складывать сразу несколько экземпляров, может дополнить условия задачи, ну и ремарку чтоб перегрузку __add__ не искали, как я. Кстати, есть ли решения, когда мы не создаём экземпляр объекта внутри __add__? Возвращаем число вместо объекта, а дальше оператор сложения уже с другими типами. Если создать два __add__ с разными параметрами, то вызывается последний

2020-11-18 12:28 UTC, IlyaOrlov commented on Practice/VadikV/L8/task10.py
> +        return str(self._round + other._round) + "," + str(tmpsum).zfill(3)
>>а так же при делении экземпляров - число, при делении экземпляра на число - экземпляр
Согласен. Получается логично.
>>Кстати, есть ли решения, когда мы не создаём экземпляр объекта внутри add?
Можно разные подходы реализовать (насколько фантазии хватит). Но лучше, чтоб работа функции была интуитивно понятна.
Насчет дополнения условий... Я придерживаюсь мнения, что решение сопутствующих проблем и сомнения в выборе того или иного решения на этапе обучения дают лучший результат, чем простое следование однозначным установкам)

2020-11-18 12:29 UTC, IlyaOrlov approved these changes

2020-11-18 12:29 UTC, merged