tasks lec5, lec8
IlyaOrlov/PythonCourse2 pull request #70
Opened 2020-11-15 18:16 UTC by Irene-lab80

2020-11-15 19:08 UTC, IlyaOrlov requested changes

2020-11-15 19:08 UTC, IlyaOrlov commented on Practice/IrinaZ/3.range.py
> +    if stop == 0:
А если будет, например, такой вариант использования: my_range(5, 0, -1)?

2020-11-15 19:08 UTC, IlyaOrlov commented on Practice/IrinaZ/7.copyfile.py
> +    except FileExistsError:
Чтоб такое исключение генерировалось, надо открывать файл в режиме "x", а не "w".

2020-11-15 19:08 UTC, IlyaOrlov commented on Practice/IrinaZ/9.User.py
> +print(w1._salary + w2._salary)
Хорошо ли это, обращаться напрямую к атрибуту, который вы сами сделали защищенным?

2020-11-18 14:44 UTC, IlyaOrlov commented on Practice/IrinaZ/7.copyfile.py
> +    except FileExistsError:
При этом оба файла должны быть открыты в одном режиме: либо в текстовом, либо в бинарном.

2020-11-18 14:44 UTC, IlyaOrlov commented on Practice/IrinaZ/7.copyfile.py
> +copyfile(file_1, file_2)  # NameError: name 'file_1' is not defined
Так, наверное, надо определить переменные file1 и file2.

2020-11-18 14:44 UTC, IlyaOrlov commented on Practice/IrinaZ/3.range.py
> +    if stop == 0:
Хорошо. А теперь еще такой вариант: my_range(5) - чтоб генерировались элементы от 0 до 5.

2020-11-18 15:16 UTC, Irene-lab80 commented on Practice/IrinaZ/3.range.py
> +    if stop == 0:
Я понимаю, что надо поменять местами stop и start и сделать start = 0. Но теперь когда я пишу это, оно не работает для положительного шага.  Я не знаю что я делаю не так.

2020-11-18 15:17 UTC, Irene-lab80 commented on Practice/IrinaZ/7.copyfile.py
> +    except FileExistsError:
окей, поняла

2020-11-18 16:14 UTC, IlyaOrlov commented on Practice/IrinaZ/3.range.py
> +    if stop == 0:
А вы сделайте по умолчанию stop=None, а то сейчас, когда указан только один аргумент и когда my_range(5, 0) - разницы для алгоритма нет.

2020-11-18 16:31 UTC, IlyaOrlov approved these changes

2020-11-18 16:31 UTC, merged