Lec 9
IlyaOrlov/PythonCourse2 pull request #71
Opened 2020-11-18 18:20 UTC by dm2485

2020-11-19 11:11 UTC, IlyaOrlov requested changes

2020-11-19 11:11 UTC, IlyaOrlov commented on Practice/d_egorov/lec_8_cw3.py
> +def my_range(stop, start = 0, step = 1):
Порядок аргументов должен быть такой же, как у стандартного range(). Это важный в рамках данной задачи нюанс. Должны работать следующие варианты использования:
print(my_range(0, 10,))
print(my_range(10, 1, -1))

2020-11-19 11:11 UTC, IlyaOrlov commented on Practice/d_egorov/lec_9_hw1.py
> +if __name__ == '__main__':
Какой из 3-х вариантов показал лучший по времени результат?

2020-11-20 11:36 UTC, IlyaOrlov commented on Practice/d_egorov/lec_8_cw3.py
> +def my_range(stop, start = 0, step = 1):
А как же теперь print(my_range(10))?

2020-11-23 11:51 UTC, dm2485 commented
Исправил

2020-11-23 12:29 UTC, IlyaOrlov commented on Practice/d_egorov/lec_9_hw1.py
> +    p1.start()
Их бы тоже списком обрабатывать

2020-11-23 12:30 UTC, IlyaOrlov commented
> Исправил

Остался еще вопрос по lec_9_hw1.py: кто быстрее?

2020-11-23 15:22 UTC, dm2485 commented
> 
> 
> > Исправил
> 
> Остался еще вопрос по lec_9_hw1.py: кто быстрее?

Я оставил комментарий в исходнике что мультипроцессинг быстрее.

2020-11-23 19:06 UTC, IlyaOrlov commented
> > > Исправил
> > 
> > 
> > Остался еще вопрос по lec_9_hw1.py: кто быстрее?
> 
> Я оставил комментарий в исходнике что мультипроцессинг быстрее.

ОК. Увидел)

2020-11-23 19:06 UTC, IlyaOrlov approved these changes

2020-11-23 19:06 UTC, merged