Teterin Roman added Test_Work_1
IlyaOrlov/PythonCourse2 pull request #73
Opened 2020-11-19 13:55 UTC by rateterin

2020-11-19 18:19 UTC, IlyaOrlov requested changes

2020-11-19 18:19 UTC, IlyaOrlov commented on Practice/Teterin_Roman/Test_Work_1/test9.py
> +        if 'salary' in locals():
В чем смысл этой проверки (и для name, и для age))?

2020-11-20 09:13 UTC, rateterin commented on Practice/Teterin_Roman/Test_Work_1/test9.py
> +        if 'salary' in locals():
проверка существования переменной. согласен, в таком виде в ините вообще безсмысленно. переделал.

2020-11-20 11:24 UTC, IlyaOrlov commented on Practice/Teterin_Roman/Test_Work_1/test9.py
> +        if 'salary' in locals():
В init воркера тоже как-то странно выглядит.

2020-11-23 07:03 UTC, IlyaOrlov approved these changes

2020-11-23 07:03 UTC, merged