D egorov
IlyaOrlov/PythonCourse2 pull request #78
Opened 2020-11-24 11:46 UTC by dm2485

task 1,2 lec 10

2020-11-26 20:41 UTC, IlyaOrlov requested changes

2020-11-26 20:41 UTC, IlyaOrlov commented on Practice/d_egorov/lec_10_hw2_server.py
> +    name = conn.recv(1024).decode()
Так, конечно, тоже можно. Но все же нужна более универсальная реализация, позволяющая упаковывать и посылать по сети целого пользователя, независимо от его атрибутов (например, с использованием pickle).

2020-12-05 18:07 UTC, dm2485 commented on Practice/d_egorov/lec_10_hw2_server.py
> +    name = conn.recv(1024).decode()
Исправил

2020-12-05 22:01 UTC, IlyaOrlov approved these changes

2020-12-05 22:01 UTC, merged