Add files via upload
IlyaOrlov/PythonCourse2 pull request #84
Opened 2020-12-06 14:01 UTC by Xanamas

Lec.8 task 10

2020-12-06 22:06 UTC, IlyaOrlov requested changes

2020-12-06 22:06 UTC, IlyaOrlov commented on Practice/OxanaM/Les_8_10.py
> +            spam_ins = Money(spam_rub, spam_kop)
А вот здесь интересно получается... если мы деньги делим на деньги, должны ли в итоге получиться деньги? Например, нужно раздать 100 рублей по 5 рублей на человека...  На сколько человек хватит денег? Ответ: на 100 // 5 = 20 **человек**

2020-12-07 17:40 UTC, Xanamas commented on Practice/OxanaM/Les_8_10.py
> +            spam_ins = Money(spam_rub, spam_kop)
Да, поправила

2020-12-07 20:42 UTC, IlyaOrlov approved these changes

2020-12-07 20:42 UTC, merged