additional tasks
IlyaOrlov/PythonCourse2 pull request #87
Opened 2020-12-08 18:18 UTC by dm2485

2020-12-08 20:15 UTC, IlyaOrlov requested changes

2020-12-08 20:15 UTC, IlyaOrlov commented on Practice/d_egorov/addtask1.py
> +def my_func(lst):
Элементы в новом списке должны быть расположены "в порядке возрастания **количества вхождений этих элементов в изначальный список**".

2020-12-08 20:15 UTC, IlyaOrlov commented on Practice/d_egorov/addtask2.py
> +        self.data = self._socket.recv(self.data_size)
Здесь мы считываем все сразу и потом поэлементно обходим. А надо именно запрашивать по одному байту: recv(1).

2020-12-09 11:38 UTC, dm2485 commented on Practice/d_egorov/addtask2.py
> +        self.data = self._socket.recv(self.data_size)
Исправил. Но не знаю что в цикле iter сделать  точкой завершения. Поэтому поставил чтение с перерывами до 1024 байт

2020-12-09 11:38 UTC, dm2485 commented on Practice/d_egorov/addtask1.py
> +def my_func(lst):
Исправил, пропустил когда читал задание.

2020-12-09 20:13 UTC, IlyaOrlov commented on Practice/d_egorov/addtask2.py
> +        self.data = self._socket.recv(self.data_size)
Да, теперь лучше. Можно сделать, чтоб в самом начале сервер присылал размер последующих данных (считать его в init, а потом уже читать побайтово). Либо читать, пока хоть что-то считывается (res != None). Либо пока не считается какой-нибудь заранее оговоренный специальный символ.

2020-12-09 20:18 UTC, IlyaOrlov approved these changes

2020-12-09 20:19 UTC, merged