Babichev
IlyaOrlov/PythonCourse2 pull request #9
Opened 2020-09-27 11:04 UTC by babnikolay

2020-09-27 12:33 UTC, IlyaOrlov commented on Practice/Babichev/practice2/compare_numbers.py
> +x = input()
Можно писать сразу: x = input('Введите число x ')

2020-09-27 12:34 UTC, IlyaOrlov commented on Practice/Babichev/practice2/compare_numbers.py
> +        print(str(a) + " is bigger")
Для вывода лучше использовать форматную строку. Получается короче и понятней:
print(f"{a} is bigger")

2020-09-27 12:35 UTC, IlyaOrlov requested changes

2020-09-27 12:35 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +import sys
Ожидаются ваши комментарии по ошибкам в данном файле.

2020-09-28 14:15 UTC, IlyaOrlov requested changes

2020-09-28 14:15 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +    def rename(self, dirname, output):  # тупая система, предполагает что rename надо сделать static
Отчего же сразу тупая? Просто из-за кривого отступа mp3s PyCharm считает, что rename никак не использует поля объекта (через self), поэтому и предлагает сделать метод статическим.

2020-09-28 14:15 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +            hashname = self.generateName() + '.mp3'     # опечатка в слове hashname; отсутствует атрибут generateName в классе Shuffler
Опечатка? А как правильно?

2020-09-28 14:15 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +            f.write(str(self.map))    # попытка записи в файл, открытый на запись
Может, открытый на чтение?

2020-09-28 14:15 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +        return hashlib.md5(str(seed)).hexdigest()      # неожиданный тип str, должен быть другой тип
Для кого тип str неожиданный?

2020-09-28 14:15 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +    Shuffler = shuffler()   # Неразрешенная ссылка "shuffler" - нет такой функции
shuffler - это было название класса, которое вы поменяли на Shuffler.

2020-09-28 18:17 UTC, babnikolay commented on Practice/Babichev/practice1/pep8task.py
> +            f.write(str(self.map))    # попытка записи в файл, открытый на запись
да, на чтение

2020-09-28 18:19 UTC, babnikolay commented on Practice/Babichev/practice1/pep8task.py
> +    Shuffler = shuffler()   # Неразрешенная ссылка "shuffler" - нет такой функции
здесь написано имя функции, которой нет.
нужен ли здесь класс и как его правильно вызвать я ещё не знаю, поэтому написал, что знаю

2020-09-28 18:20 UTC, babnikolay commented on Practice/Babichev/practice1/pep8task.py
> +        return hashlib.md5(str(seed)).hexdigest()      # неожиданный тип str, должен быть другой тип
это выдала pycharm
возможно для md5
я не знаю, что обозначают точки в данных случаях

2020-09-28 18:21 UTC, babnikolay commented on Practice/Babichev/practice1/pep8task.py
> +            hashname = self.generateName() + '.mp3'     # опечатка в слове hashname; отсутствует атрибут generateName в классе Shuffler
не знаю

2020-09-28 18:22 UTC, babnikolay commented on Practice/Babichev/practice1/pep8task.py
> +    def rename(self, dirname, output):  # тупая система, предполагает что rename надо сделать static
потому и тупая, что не может отличить отступ от вызова функции ))))

2020-09-28 19:37 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +        return hashlib.md5(str(seed)).hexdigest()      # неожиданный тип str, должен быть другой тип
Да, для md5. Она ожидает набор байтов, а ей передается обычная строка. Все-таки стоило указывать только те ошибки, которые вы нашли и поняли сами, т.к. задание заключалось не в том, чтоб переводить замечания PyCharm, а в том чтоб сверить файл с правилами PEP8, описанными в лекции.

2020-09-28 19:43 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +    def rename(self, dirname, output):  # тупая система, предполагает что rename надо сделать static
Это не вызов функции, а только ее определение. Вызов же метода rename осуществляется в строках 61 и 63. Тело функции определяется отступами. Поэтому PyCharm здесь рассуждает весьма здраво, не только сообщая об ошибках, но и предполагая их возможное решение.

2020-09-28 19:45 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +            hashname = self.generateName() + '.mp3'     # опечатка в слове hashname; отсутствует атрибут generateName в классе Shuffler
Так и нет никакой опечатки. PyCharm просто предупреждает, что слово hashname в его словаре отсутствует.

2020-09-28 19:47 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +    Shuffler = shuffler()   # Неразрешенная ссылка "shuffler" - нет такой функции
Здесь было написано то же слово, что и в строке 9. И это замечание PyCharm здесь появилось только после изменения слова shuffler в строке 9 на Shuffler.

2020-09-28 19:48 UTC, IlyaOrlov commented on Practice/Babichev/practice1/pep8task.py
> +            f.write(str(self.map))    # попытка записи в файл, открытый на запись
Стоит скорректировать комментарий

2020-09-29 18:34 UTC, IlyaOrlov approved these changes

2020-09-29 18:34 UTC, merged